/*
 * SPI_Configuration.h
 *
 *  Created on: Mar 25, 2025
 *      Author: mylap
 */

#ifndef SPI_CONFIGURATION_H_
#define SPI_CONFIGURATION_H_


#define SPI_uint32TIMEOUT					10000UL

#define SPI_DATA_ORDER						SPI_DATA_MSP_FIRST

#define SPI_MASTER_SLAVE_SELECT				SPI_MASTER

#define SPI_CLOCK_POLARITY					SPI_RISING_LEADING_FALLING_TRAILING

#define SPI_CLOCK_PHASE						SPI_SAMPLE_LEADING_SETUP_TRAILING

#define SPI_CLOCK_RATE						SPI_FREQ_DIVIDED_BY_16

#define SPI_INTERRUPT_ENABLE_MODE			SPI_INTERRUPT_DISABLE

#define SPI_ENABLE_MODE						SPI_ENABLE


#endif /* SPI_CONFIGURATION_H_ */
